#!/usr/bin/perl -w
# See bottom of file for license and copyright information
use strict;
use warnings;

use FindBin qw( $Bin );

use CGI;
my $q = CGI->new;


my $actual_dir = `pwd`;

print $q->header('text/plain');

print "I'm actually in $actual_dir\n";
print "and FindBin(\$Bin) thinks i'm in $Bin\n";
print "FindBin version ".$FindBin::VERSION."\n";


