#! /usr/bin/perl

use strict;
use warnings;

use Pod::Text::Overstrike;

my $parser = Pod::Text::Overstrike->new(margin => 0, indent => 2, width => 78);
$parser->output_fh(*STDOUT);
$parser->parse_string_document(<<EOS);
=pod

=over 10

=item 12345678

A

=item B<12345678>

B

=item 1

C

=item B<1>

D

=back
EOS
