#!perl -w

use strict;
use warnings;
use Term::ShellUI;
my $term = Term::ShellUI->new(app => "fastly", keep_quotes => 0,  history_file => $ENV{HOME}."/.fastly_history", prompt => "fastly> ");

$term->{debug_complete}=5;

print 'Using '.$term->{term}->ReadLine."\n";
use Term::ANSIColor qw(:constants);

my $basecommands = { 
    "show" => {
        desc => "Display objects",
        cmds => {
            service => {
                desc => "Show a service",
                minargs => 1,
                maxargs => 3,
                args => [sub { ['foo','bar'] }, sub { ['version'] }, sub { [1,2,3] }],
                proc => sub { print "Hello\n" },
            },
        }
    },
    "quit" => { 
        desc => "Quit", 
        maxargs => 0,
        method => sub { shift->exit_requested(1) },
        exclude_from_history => 1,
    },
};

$term->commands($basecommands);
$term->run(@ARGV);