--- Makefile.PL.orig	Sun Apr 15 01:22:30 2007
+++ Makefile.PL	Thu Apr 26 20:43:32 2007
@@ -7,7 +7,8 @@
     AUTHOR              => 'Damian Conway <DCONWAY@CPAN.org>',
     VERSION_FROM        => 'lib/Perl6/Perldoc.pm',
     ABSTRACT_FROM       => 'lib/Perl6/Perldoc.pm',
-    EXE_FILES           => ['bin/perldoc2text','bin/perldoc2xhtml'],
+    EXE_FILES           => ['bin/perldoc2text','bin/perldoc2xhtml',
+                            'bin/perldoc2xhtml_enhanced'],
     PL_FILES            => {},
     PREREQ_PM => {
         'Filter::Simple' => 0,
