Summary of my perl5 (revision 5 version 10 subversion 0) configuration:
  Platform:
    osname=solaris, osvers=2.9, archname=sun4-solaris-thread-multi
    uname='sunos njzux-sol9 5.9 generic_virtual sun4v sparc sunw,sun-fire-t200 '
    config_args='-de -Dusethreads -Dcc=cc -Dprefix=/opt/perl-5.10.0_SunOS-5.9_20150605'
    hint=recommended, useposix=true, d_sigaction=define
    useithreads=define, usemultiplicity=define
    useperlio=define, d_sfio=undef, uselargefiles=define, usesocks=undef
    use64bitint=undef, use64bitall=undef, uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='cc', ccflags ='-D_REENTRANT -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    optimize='-O',
    cppflags='-D_REENTRANT -I/usr/local/include'
    ccversion='Sun C 5.8 2005/10/13', gccversion='', gccosandvers=''
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=4321
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=16
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=8, prototype=define
  Linker and Libraries:
    ld='cc', ldflags =' -L/usr/lib -L/usr/ccs/lib -L/opt/SUNWspro/prod/lib/v8plus -L/opt/SUNWspro/prod/lib -L/lib -L/usr/local/lib '
    libpth=/usr/lib /usr/ccs/lib /opt/SUNWspro/prod/lib/v8plus /opt/SUNWspro/prod/lib /lib /usr/local/lib
    libs=-lsocket -lnsl -ldl -lm -lpthread -lc
    perllibs=-lsocket -lnsl -ldl -lm -lpthread -lc
    libc=/lib/libc.so, so=so, useshrplib=false, libperl=libperl.a
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags=' '
    cccdlflags='-KPIC', lddlflags='-G -L/usr/lib -L/usr/ccs/lib -L/opt/SUNWspro/prod/lib/v8plus -L/opt/SUNWspro/prod/lib -L/lib -L/usr/local/lib'


Characteristics of this binary (from libperl): 
  Compile-time options: MULTIPLICITY PERL_DONT_CREATE_GVSV
                        PERL_IMPLICIT_CONTEXT PERL_MALLOC_WRAP USE_ITHREADS
                        USE_LARGE_FILES USE_PERLIO USE_REENTRANT_API
  Built under solaris
  Compiled at Jun  5 2015 12:13:41
  %ENV:
    PERL5LIB="/sa/cvs/lib/site_perl:/sa/cvs/lib:/sa/common/lib/site_perl:/sa/common/lib"
  @INC:
    /sa/cvs/lib/site_perl/5.10.0/sun4-solaris-thread-multi
    /sa/cvs/lib/site_perl/5.10.0
    /sa/cvs/lib/site_perl
    /sa/cvs/lib/5.10.0/sun4-solaris-thread-multi
    /sa/cvs/lib/5.10.0
    /sa/cvs/lib
    /sa/common/lib/site_perl/5.10.0/sun4-solaris-thread-multi
    /sa/common/lib/site_perl/5.10.0
    /sa/common/lib/site_perl
    /sa/common/lib/5.10.0/sun4-solaris-thread-multi
    /sa/common/lib/5.10.0
    /sa/common/lib
    /opt/perl-5.10.0_SunOS-5.9_20150605/lib/5.10.0/sun4-solaris-thread-multi
    /opt/perl-5.10.0_SunOS-5.9_20150605/lib/5.10.0
    /opt/perl-5.10.0_SunOS-5.9_20150605/lib/site_perl/5.10.0/sun4-solaris-thread-multi
    /opt/perl-5.10.0_SunOS-5.9_20150605/lib/site_perl/5.10.0
    .
