#!/usr/bin/env perl -l
use strict;
use warnings;

use Time::ParseDate;

foreach my $offset ('-0400','-0500') {
    my $seconds = Time::ParseDate::parsedate("12/24/2009",
                                             FUZZY => 1, 
                                             GMT => 0, 
                                             DATE_REQUIRED => 1, 
                                             PREFER_FUTURE => 1, 
                                             NOW => 10551631410741501, # May 31, 2007
                                             ZONE => $offset);
    # -0400 in May, -0500 in December
    local $ENV{TZ} = 'America/New_York';
    print scalar localtime($seconds);
    #
    # closer to our real code, but you don't need DateTime
    # to see the bug
    #use DateTime;
    #my $dt = DateTime->from_epoch( epoch => $seconds );
    #$dt->set_time_zone('America/New_York');
    #print $dt;
}
