#!/usr/bin/perl -w

use strict;
use Mail::IMAPClient;

my $username = "rasjidw";
my $password = "godisok";

my $host = "localhost";
my $port = 1143;
my $debug = 1;

my $imapconn = Mail::IMAPClient->new( Server   => $host,
			       Port     => $port,
			       User     => $username,
			       Password => $password,
			       Fast_IO  => 1,
			       Uid      => 1,
			       Peek     => 1,
			       Debug    => $debug,
			     )
  or die "can't open imap connection on [$host] with user [$username]\n";

my $sep = $imapconn->separator();

print "Separator returned is '$sep'\n";

$imapconn->logout();

1;
