#!/usr/bin/perl

use strict;
use warnings;
 
use XML::Parser;

my $p=XML::Parser->new( Handlers => { Char    => sub { printf "char    : [%s]\n", show_lf( $_[1]);}, 
                                      Default => sub { printf "default : [%s]\n", show_lf( $_[1]);}, 
                                    }
                       ); 

$p->parse( "<doc>foo</doc>\n \n");

sub show_lf
  { my( $string)= @_;
    $string=~ s{\n}{\\n}g;
    return $string;
  }
