#!/usr/local/bin/perl -w

use strict;
use Data::Dump qw(pp);
use WWW::Mechanize;
use open IO => ':locale';

$| = 1;

my $mech = WWW::Mechanize->new;
$mech->get('http://www.mainpost.de/anzeigen/immobilien/suchen/');
$mech->follow_link(
    text      => 'Jetzt suchen',
    url_regex => qr(//www\.mainpost\.de/)
);

my $text = "\xA0Vermietungen";

sub test {
    print shift() . ': ';
    my $link = $mech->find_link( text => $text );
    print defined $link ? pp( $link->text, $link->url ) : 'No link found.', "\n";
}

test(__LINE__);
utf8::upgrade($text);
test(__LINE__);
