#!/usr/bin/env perl

use strict;
use warnings;
use Data::Dumper;

my $path = shift or die "Usage: $0 <filename>\n";

open my $fh, '<:raw:eol(LF-Native)', $path
  or die "unable to open '$path': $!";

while (<$fh>) {
  chomp;
  my @row = split /\t/;
  print Dumper(\@row), "\n";
}
