package Bio::MUST::Provision::Hmmer;
# ABSTRACT: Internal class for app provisioning system

# AUTOGENERATED CODE! DO NOT MODIFY THIS FILE!

use Modern::Perl '2011';
use Carp;

use parent qw(App::Provision::Tiny);


sub deps { qw(brew) }

sub condition {
    my $self = shift;

    my $condition = qx{which hmmsearch} =~ m/hmmsearch$/xms;
    carp 'Note: HMMER executable not found; installing with HomeBrew...'
        unless $condition;

    return $condition ? 1 : 0;
}

sub meet {
    my $self = shift;

    $self->recipe(
        ['brew tap brewsci/bio'],
        ['brew install hmmer'],
    );
}

1;
