#!/usr/bin/perl

use warnings;
use strict;

use Net::SNMP;
use SNMP;
use Data::Dumper;
$Data::Dumper::Useqq = 1;
$| = 1;

my $switchaddr = '192.168.58.254';
my $community = 'snmp_poll';


my $snmp = SNMP::Session->new (
    DestHost => $switchaddr,
    Community => $community,
    Version => '2c',
) or die "Unable to connect to $switchaddr via SNMP\n";

my $net_snmp = Net::SNMP->session (
    -hostname => $switchaddr,
    -version => '2c',
    -community => $community,
) or die "Unable to connect to $switchaddr via Net::SNMP\n";

show_modules();

for my $oid (qw/
    .1.3.6.1.2.1.1 
    .1.3.6.1.2.1.2.2 
    .1.3.6.1.2.1.16.19
    .1.3.6.1.2.1.17.4.3.1.1
/) {

    my $response;
    
    print "\nTrying Net::SNMP->get_table on $oid\n=========================\n";
    eval { $response = $net_snmp->get_table (-baseoid => $oid) };
    if ($@) {
        print "FAILED: $@\n";
    }
    else {
        print Dumper $response;
    }
    
    print "\nTrying SNMP->gettable on $oid\n=========================\n";
    eval { $response = $snmp->gettable ($oid) };
    if ($@) {
        print "FAILED: $@\n";
    }
    else {
        print Dumper $response;
    }
}

sub show_modules {
    no strict 'refs';
    printf "Perl Version: %vd\n\nCurrently loaded modules:\n===========================\n", $^V;
    for my $mod (sort keys %INC) {
        $mod =~ s/\.pm$// or next;
        $mod =~ s!/!::!g;
        printf "%s => %s\n", $mod, $mod->VERSION || 'Unknown';
    }

    print "\n";
}
