#!/usr/bin/perl

use strict;
use warnings;

use IO::File;
use IO::InnerFile;
use GTop;

my $fullpath = '/path/to/4GB_file';

my $fh = IO::File->new($fullpath, 'r');
binmode($fh);
my $ifh = IO::InnerFile->new($fh, 0, 100);
my $gtop = GTop->new;

my $chunkref2 = do { local $/; <$ifh> };
printf "mem: %s\n", $gtop->proc_mem($$)->rss;
printf "length: %s\n", length $chunkref2;

