# This file was generated by running "update-rt-siteconfig-4".
#
# While local modifications will not be overwritten without permission,
# it is recommended the they are instead placed in 
# /etc/request-tracker4/RT_SiteConfig.d
#
# Note that modifications to the RT_SiteConfig.d directory won't 
# take effect until the update command mentioned above is run again.

# start /etc/request-tracker4/RT_SiteConfig.d/40-timezone
# dynamically find out the current timezone

my $zone = "UTC";
$zone=`/bin/cat /etc/timezone`
    if -f "/etc/timezone";
chomp $zone;

Set($Timezone, $zone);


# end   /etc/request-tracker4/RT_SiteConfig.d/40-timezone
# start /etc/request-tracker4/RT_SiteConfig.d/50-debconf
# THE BASICS:

Set($rtname, 'rt.lif-dev-dio01');
Set($Organization, 'lif-dev-dio01');

Set($CorrespondAddress , 'rt@lif-dev-dio01');
Set($CommentAddress , 'rt-comment@lif-dev-dio01');

# THE WEBSERVER:

Set($WebPath , "/rt");
Set($WebBaseURL , "http://lif-dev-dio01");

# end   /etc/request-tracker4/RT_SiteConfig.d/50-debconf
# start /etc/request-tracker4/RT_SiteConfig.d/51-dbconfig-common
# THE DATABASE:
# generated by dbconfig-common

# map from dbconfig-common database types to their names as known by RT
my %typemap = (
    mysql   => 'mysql',
    pgsql   => 'Pg',
    sqlite3 => 'SQLite',
);

Set($DatabaseType, $typemap{sqlite3} || "UNKNOWN");

Set($DatabaseHost, 'localhost');
Set($DatabasePort, '');

Set($DatabaseUser , '');
Set($DatabasePassword , '');

Set(@ReferrerWhitelist, qw(rt.lif-dev-dio01.lonres.org:80));

# SQLite needs a special case, since $DatabaseName must be a full pathname
my $dbc_dbname = 'rtdb'; if ( "sqlite3" eq "sqlite3" ) { Set ($DatabaseName, '/var/lib/dbconfig-common/sqlite3/request-tracker4'$
# end   /etc/request-tracker4/RT_SiteConfig.d/51-dbconfig-common
1;

# hillya03 added RT SLA plugin
Set(@Plugins,(qw(RT::Extension::SLA)));

# hillya03 added RT SLA code
%RT::ServiceBusinessHours = (
        0 => { Name => 'Sunday',Start => 'undef', End => 'undef' },
        1 => { Name => 'Monday', Start => '09:00', End => '18:00' },
        2 => { Name => 'Tuesday', Start => '09:00', End => '18:00' },
        3 => { Name => 'Wednesday', Start => '09:00', End => '18:00' },
        4 => { Name => 'Thursday', Start => '09:00', End => '18:00' },
        5 => { Name => 'Friday', Start => '09:00', End => '18:00' },
        6 => { Name => 'Saturday', Start => 'undef', End => 'undef' },
);

%RT::ServiceAgreements = (
        QueueDefault => {
                'General' => 'Low',
                '44lif' => 'Low',
                'CHL' => 'Low',
        },

        Levels => {
                'Critical' => {
                        Resolve => { BusinessMinutes => 60*4 }, # 4 business hours
                },
                'High' => {
                        Resolve => { BusinessMinutes => 60*8 }, # 1 business day
               },
                'Medium' => {
                        Resolve => { BusinessMinutes => 60*8*3 }, # 3 business days
                },
                'Low' => {
                        Resolve => { BusinessMinutes => 60*8*5 }, # 5 business days
                },
                'Service' => {
                        Resolve => { BusinessMinutes => 60*8*10 }, # 10 business days
                },
        },
);
