#!/usr/bin/env perl

use 5.010;

package Foo;

use Moose;

has bar => (
    is      => 'rw',
    isa     => 'Maybe[Str]',
);

package main;

my $example = Foo->new();
$example->bar('whatever');
say $example->bar();
