## no critic (ProhibitHardTabs, RequireRcsKeywords)
## name Basic failures
## failures 7
## cut

 print;

	 print;

 	print;

	 	print;
 print;
	 print;
 	print;
	 	print;
#-----------------------------------------------------------------------------

## name Basic passing
## failures 0
## cut

print;
	print;
				print;

#-----------------------------------------------------------------------------

## name Heredoc
## failures 0
## cut

my $var = <<END;
	var
 	var
	 var

 	var

	 var
END

