
=head1 NAME

wikiup - upload content to a topic on a Foswiki or TWiki wiki site.

=head1 SYNOPSIS

wikiup [options] destination files...

=head1 DESCRIPTION

=head2 Specifying the destination topic

=head1 OPTIONS AND ARGUMENTS

The required arguments (which typically follow any options on the
command line) are:

