#!/usr/bin/perl

package p;
use Moose;
with "MooseX::Getopt";

has "arg" => (
	is  => "ro",
	isa => "Str",
	default => 'a',
); 

1;

package main;

print join "\n", $Getopt::Long::VERSION,
	$Getopt::Long::Descriptive::VERSION,
	$Moose::VERSION,
	$MooseX::Getopt::VERSION,
	"\n";

my $o=p->new_with_options; 
print $o->arg, "\n";

