Name:           perl-HTML-TextToHTML
Version:        2.51
Release:        1%{?dist}
Summary:        txt2html Perl module
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/txt2html/
Source0:        http://www.cpan.org/modules/by-module/HTML/txt2html-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl >= 1:5.8.1
BuildRequires:  perl(Getopt::ArgvFile)
BuildRequires:  perl(Module::Build)
BuildRequires:  perl(Test::Distribution)
BuildRequires:  perl(Test::More)
BuildRequires:  perl(YAML::Syck)
Requires:       perl(Getopt::ArgvFile)
Requires:       perl(YAML::Syck)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
It supports headings, tables, lists, simple character markup, and
hyperlinking, and is highly customizable. It recognizes some of the
apparent structure of the source document (mostly whitespace and
typographic layout), and attempts to mark that structure explicitly using
HTML. The purpose for this tool is to provide an easier way of converting
existing text documents to HTML format, giving something nicer than just
whapping the text into a big PRE block.

%prep
%setup -q -n txt2html-%{version}

%build
%{__perl} Build.PL installdirs=vendor
./Build

%install
rm -rf $RPM_BUILD_ROOT

./Build install destdir=$RPM_BUILD_ROOT create_packlist=0
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
./Build test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes DEVNOTES old_version.txt README TODO version.txt
%{perl_vendorlib}/*
%{_mandir}/man3/*
%{_mandir}/man1/*
%{_bindir}/*

%changelog
* Thu Jul 21 2011 Michael R. Davis (mdavis@stopllc.com) 2.51-1
- Specfile autogenerated by cpanspec 1.78.
