#!/usr/bin/env perl

use JSON::XS qw<decode_json>;
use XML::XML2JSON;
use Test::More;

my $XML2JSON = XML::XML2JSON->new();

my $DOM1 = $XML2JSON->obj2dom( { 'foo' => 'bar' } );
ok( $DOM1 =~ m{<\?xml version="1\.0" encoding="UTF-8"\?>}, "ref1" );

my $DOM2 = $XML2JSON->obj2dom( { '@foo' => 'bar' } );
ok( $DOM2 =~ m{<\?xml version="1\.0" encoding="UTF-8"\?>}, "ref2" );

done_testing();
