#!/usr/bin/perl

use strict;
use warnings;

use Scalar::Util qw(weaken); 
my $NB_ELT_INIT  = 10000;
my $NB_ELT_MAX   = 40000;
my $STEP         = 5000;

my $nb_elt= $NB_ELT_INIT;
while( $nb_elt <  $NB_ELT_MAX)
  {
      { my $t= {};
        foreach (1..$nb_elt)
          { my $e;
            $e->{parent}= $t;
            weaken( $e->{parent});
            if( my $prev_sibling= $t->{last_child})
              { $prev_sibling->{next_sibling}= $e; }
            else
              { $t->{first_child}= $e; }
            $t->{last_child}= $e;
          }
        weaken $t->{last_child}; # segfault even when this line is commented out!!!
        warn "tree created \n"; 
      }
    warn "tree out of scope OK ($nb_elt)\n";
    $nb_elt += $STEP;
  }

