HELLO1 = "C:\Temp\directory with spaces\hello.exe"
HELLO2 = "C:\Temp\directory with spaces\hello.exe" arg
HELLO3 = "C:\Temp\directory with spaces\hello.exe" "arg"

all :
	@echo $(HELLO1)
	@$(HELLO1)
	@echo $(HELLO2)
	@$(HELLO2)
	@echo $(HELLO3)
	@$(HELLO3)
