<?xml version="1.0" encoding="UTF-8"?>
<definitions 
  xmlns="http://schemas.xmlsoap.org/wsdl/" 
  xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
  xmlns:tns="http://web01-dev/prime" 
  targetNamespace="http://web01-dev/prime">

  <types>
    <xsd:schema elementFormDefault="qualified" targetNamespace="http://web01-dev/prime">
      <xsd:element name="PrimeRequest" type="xsd:integer"/>
      <xsd:element name="PrimeResponse" type="xsd:boolean"/>
    </xsd:schema>
  </types>

  <message name="PrimeRequest">
    <part name="parameters" element="tns:PrimeRequest"/>
  </message>
  <message name="PrimeResponse">
    <part name="parameters" element="tns:PrimeResponse"/>
  </message>
  
  <portType name="PrimeServiceSoapType">

    <operation name="IsPrime">
      <documentation>Check to see if the number is prime!!</documentation>
      <input message="tns:PrimeRequest"/>
      <output message="tns:PrimeResponse"/>
    </operation>

  </portType>

  <binding name="PrimeServiceSoapBinding" type="tns:PrimeServiceSoapType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="IsPrime">
      <soap:operation soapAction="/IsPrime" style="document"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>

  <service name="PrimeService">
    <documentation>Magic service that will tell you if the integer that you submitted is a prime number or not.</documentation>
    <port name="PrimeServiceSoap" binding="tns:PrimeServiceSoapBinding">
      <soap:address location="http://web01-dev/v1"/>
    </port>
  </service>

</definitions>
