#!/usr/local/bin/perl

use CGI qw( :standard );

print "Version=$CGI::VERSION\n";
print 'First word "CGI" eaten with function form', "\n";
print li( 'I', 'like', 'CGI' ), "\n";
print li( 'CGI', 'is', 'fun' ), "\n";
print p( 'CGI', 'is', 'fun' ), "\n";

my $q = CGI->new;
print 'First word "CGI" displays correctly with method form', "\n";
print $q->li( 'I', 'like', 'CGI' ), "\n";
print $q->li( 'CGI', 'is', 'fun' ), "\n";
print $q->p( 'CGI', 'is', 'fun' ), "\n";
