#!/usr/bin/env perl

use JSON::XS qw<decode_json>;
use XML::XML2JSON;
use Test::More;

is( $XML::XML2JSON::VERSION, '0.06', 'Correct version of XML::XML2JSON' );

my $ref  = decode_json '{"@version":"1.0","test":{"data":{"@attr1":"test","$t":"some test text"},"test$nstest":{"@attr1":"bar"},"@xmlns:test":"http://test.example/test","censored":{},"array":{"@perl":"awesome","item":[{"@index":"0"},{"@index":"1"},{"@index":"2"}]},"empty":{"inner":{"@c":"d"}}},"@encoding":"UTF-8"}';

for (my $i = 0; $i < 5; $i++) {
    my $XML2JSON = XML::XML2JSON->new();
    my $DOM;
    eval { $DOM = $XML2JSON->obj2dom($ref) };
    warn $@;
    ok( $DOM =~ m{<\?xml version="1\.0" encoding="UTF-8"\?>}, "Itr $i" );
}

done_testing();
