#!/usr/bin/perl
use strict;
use warnings;
use threads;

my $terminate = 0;
sub thr_func {
    print "thread started\n";

    #$SIG{'SIGTERM'} = sub { threads->exit() };

    while(1) {
        sleep(100);
    }
}

my $thr = threads->create('thr_func');
$thr->kill('SIGTERM');

