#!/usr/local/bin/perl -w
#	Resolver query() treats empty or undef name as default domain
#
use Net::DNS;

print "Net::DNS ", Net::DNS::version(), "\n";
print "Perl ", $], "\n";
system("uname -srp");


my $resolver = Net::DNS::Resolver->new( debug=>0, domain => 'example.org' );


foreach my $example ( "", undef ) {
	print "\n\nquery( ", defined $example ? "'$example'" : 'undef', " )\n";
	my $packet = $resolver->query($example, 'ANY');
	next unless $packet;
	foreach ( $packet->question ) {
		print "Q\t", $_->string, "\n";
	}
	print "\t", $packet->header->rcode, "\n";
	foreach ( $packet->answer ) {
		print "A\t", $_->string, "\n";
	}
}

exit;

