#!/usr/bin/perl

use warnings;
use strict;
use forks;
use forks::shared;

my %p :shared = (
  a => 1,
  b => 2,
  c => 3,
  d => 4,
  e => 5,
  f => 6,
);

my $a :shared = "1000";

sub fct {
  while (my ($k, $v) = each %p) {
    print "$k : $v\n";
  }
	print "a=$a\n";
}

my $pid = fork;
exit if $pid;

&fct;

