#!/usr/bin/env perl
# This document is UTF-8
 
use strict;
use warnings;
# use bytes; # UTF-8 bytestream -- but 'use bytes' is deprecated; see its docs
use utf8;	# This document is UTF-8
use Encode;	# Because the output of pbpaste is already UTF-8
		# encoded, we need to decode it back to Perl's
		# internal representation.

use Mac::Pasteboard;

binmode STDOUT, ':encoding(UTF-8)';	# Kill 'wide character in print' warning
 
Mac::Pasteboard::pbencode( 1 );	# Because I forgot to export. Fixed in next release.
pbflavor( 'public.utf8-plain-text' );

my $snowman = "☃☃☃";
system(qq{echo "$snowman" | pbcopy});
print "try pbpaste.\n";
print "LANG=$ENV{LANG}\n";
print "Mac::Pasteboard Version is $Mac::Pasteboard::VERSION\n";
print "command pbpaste => " . decode( 'UTF-8', `pbpaste`) . "\n";
print "Mac::Pasteboard::pbpaste() => " . (Mac::Pasteboard::pbpaste()) . "\n";
print "\n";
 
print "try pbcopy\n";
system(qq{echo "INIT" | pbcopy});
Mac::Pasteboard::pbcopy($snowman);
print "command pbpaste => " . decode( 'UTF-8', `pbpaste`) . "\n";
print "Mac::Pasteboard::pbpaste() => " . (Mac::Pasteboard::pbpaste()) . "\n";
print "\n";
