#!/appl/toolbox/perl5.8.8/bin/perl

use strict;
use warnings;

use lib qw(
  appl/pm/vendor/perl_modules/sol-sparc/5.8.8/lib/site_perl
  appl/pm/vendor/perl_modules/sol-sparc/5.8.8/lib
);

use Spreadsheet::WriteExcel;

my $wb = Spreadsheet::WriteExcel->new("test_nulls.xls");
my $ws1 = $wb->add_worksheet();
$ws1->write(0, 1, "B");
$ws1->write(0, 2, "C");
$ws1->write(0, 3, "D");

my $ws2 = $wb->add_worksheet();
$ws2->write(0, 0, "A");
$ws2->write(0, 2, "C");
$ws2->write(0, 3, "D");

$wb->close;
