#!/usr/perl5/5.8.4/bin/perl

eval 'exec /usr/perl5/5.8.4/bin/perl  -S $0 ${1+"$@"}'
    if 0; # not running under some shell
#
# Copyright 2004 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
#ident	"@(#)perlgcc	1.1	04/06/09 SMI"
#

use 5.8.4;
use strict;
use warnings;
our $VERSION = '1.1';

$ENV{PERL5_OVERRIDE_CONFIG} = '1';
if (exists($ENV{PERL5LIB})) {
	$ENV{PERL5LIB} =
	    "/usr/perl5/5.8.4/lib/Sun/Solaris/PerlGcc:$ENV{PERL5LIB}";
} else {
	$ENV{PERL5LIB} =
	    '/usr/perl5/5.8.4/lib/Sun/Solaris/PerlGcc';
}
exec('/usr/perl5/5.8.4/bin/perl', @ARGV)
    || die("Can't exec /usr/perl5/5.8.4/bin/perl: $!\n");
