#!/usr/bin/env perl

use strict;
use warnings;
use Hash::Diff qw(diff);
use Data::Dump qw(pp);

my %hash1=(
    array => [
        { name => "fred james" },
        { name => "john james" },
    ]
);

my %hash2=(
    array => [
        { name => "fred james" },
        { name => "john james" },
    ]
);

pp(%{ diff( \%hash1, \%hash2 ) } );



