--- #YAML:1.0
name:                Test-WWW-Mechanize
version:             1.24
abstract:            Testing-specific WWW::Mechanize subclass
license:             ~
author:              
    - Andy Lester <andy@petdance.com>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Carp::Assert::More:            0
    HTTP::Server::Simple:          0.35
    HTTP::Server::Simple::CGI:     0
    Test::Builder::Tester:         1.09
    Test::LongString:              0.12
    Test::More:                    0
    URI::file:                     0
    WWW::Mechanize:                1.24
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
