#!/usr/bin/perl

use Net::Google::Calendar;



    $cal = Net::Google::Calendar->new;
    $cal->login($g_user,$g_pass);

    @cals = $cal->get_calendars;
    for $cal_selected (@cals) {
        if ($cal_selected->title eq 'My calendar') {
           $cal->set_calendar($cal_selected);
        }
    }

    @cal_events = $cal->get_events;

    foreach $ce (@cal_events) {
       $title      = $ce->title;
       @event_when = $ce->when;
       print("$event_when[0] $event_when[1] $title\n");
    }
