#!/usr/bin/perl

use strict;
use warnings;
use Date::Parse;

print "Perl version $]\n";
print "Date::Parse version $Date::Parse::VERSION\n";
print "% uname -a\n";
system(qw(uname -a));
print "\n";

#
# My guess is that the bug occurs 50 years before the current year.
#

my @s = ( '1962-12-31 23:59:59 UTC',
          '1963-01-01 00:00:00 UTC',
          '1963-12-31 23:59:59 UTC',
          '1964-01-01 00:00:00 UTC',
          '1964-12-31 23:59:59 UTC',
          '1965-01-01 00:00:00 UTC',
          '1965-12-31 23:59:59 UTC',
          '1966-01-01 00:00:00 UTC' );
foreach my $s (@s) {
    my $t = Date::Parse::str2time($s);
    my $strptime = join(',', Date::Parse::strptime($s));
    my $printable = scalar gmtime $t;
    print "str2time(\"$s\") = $t --> $printable (strptime -> $strptime)\n";
}
