#!/usr/bin/perl

eval 'exec /usr/bin/perl  -S $0 ${1+"$@"}'
    if 0; # not running under some shell

package main;

use strict;
use warnings;
use WWW::Shorten::Bitly;

my $bitly = WWW::Shorten::Bitly->new;

print $bitly->shorten(URL => shift @ARGV), $/ while @ARGV;

__END__
=head1 NAME

C<bitly_url> - Command-line interface to WWW::Shorten::Bitly


=head1 SYNOPSIS

bitly_url http://google.com

bitly_url http://google.com http://www.youtube.com

=head1 DESCRIPTION

bitly_url shortens URLS supplied on the commandline.
You have to setup a .bitly config file to use it.

=head1 SEE ALSO

WWW::Shorten::Bitly

=head1 AUTHOR

Joerg Meltzer < joerg {at}  joergmeltzer . de >

=head1 COPYRIGHT

Copyright (c) 2009 Pankaj Jain, All Rights Reserved
<http://blog.linosx.com>.

Copyright (c) 2009 Teknatus Solutions Private Limited, All Rights Reserved
<http://www.teknatus.com>.

This program is free software; you can redistribute it and/or modify it
under the same terms as Perl itself.

=cut
