#!/usr/bin/perl

use strict;
use warnings;

use AI::Genetic::Pro;

sub fitness { return 0; }

sub terminate { return 0; }

my $ga = AI::Genetic::Pro->new(
    -fitness    => \&fitness,        # fitness function
    -terminate  => \&terminate,      # terminate function
    -type       => 'rangevector',    # type of chromosomes
    -population => 1,                # population
    -crossover  => 0.9,              # probab. of crossover
    -mutation   => 0.01,             # probab. of mutation
    -parents    => 2,                # number  of parents
    -selection  => ['Roulette'],     # selection strategy
    -strategy => [ 'Points', 2 ],    # crossover strategy
    -cache           => 0,           # cache results
    -history         => 1,           # remember best results
    -preserve        => 3,           # remember the bests
    -variable_length => 0,           # keep variable length OFF
);

$ga->init( [ [ 1, 5000 ], ] );

$ga->inject( [ [4500] ] );           # becomes -108

for my $c ( @{ $ga->people() } )
{
    print $ga->as_string($c), "\n";
}

# correctly triggers scope error
$ga->inject( [ [5500] ] );           # Value out of scope in the injected chromosome of type "rangevector": 5500

# End of file
