#!/usr/bin/perl

use warnings;
use strict;

use XML::LibXML;

my $umlauts = 'הכן';
print "UMLAUTS = $umlauts#\n";

my $doc = XML::LibXML::Document->new('1.0', 'UTF-8');
my $e = $doc->createElement('e');
$e->appendText($umlauts);
$doc->setDocumentElement($e);
print $doc->toString(1);
