#!/usr/bin/perl

use strict;
use warnings;

use GraphViz::Parse::RecDescent;

use constant GR_RULES => 'grammar.rules';

my $rulesfile = GR_RULES;
open( my $RFILE, $rulesfile ) or die "Opening $rulesfile: $!\n";

my $grammar = do { local $/; <$RFILE> };

my $graph = GraphViz::Parse::RecDescent->new($grammar);
print $graph->as_canon;

# End of file
