#!/usr/bin/perl -wT

use strict;
use diagnostics;
use warnings;
use HTML::SimpleLinkExtor;

my $html = '<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">
<HTML>
<BODY>
<A HREF="http://www.google.com">Google</A>
<A HREF="http://www.example.com">Example</A>
<A HREF="http://www.bandsman.co.uk">Bandsman</A>
<A HREF="http://www.concert-bands.co.uk">Concert Bands</A>
</BODY>
</HTML>
';

my $extor = HTML::SimpleLinkExtor->new();

unless($extor) {
	print "no links found\n";
	exit;
}

$extor->parse($html);

print "link: " . $_ . "\n" for ($extor->links);
print "href: " . $_ . "\n" for ($extor->a);
