#!/usr/bin/perl

use strict;
use warnings;
use Imager;

my $one = Imager->new( xsize=>100, ysize=>100, channels=>1 )
    or die Imager->errstr();

$one->flood_fill( x=>1, y=>1, color=>"white" );
warn "one channels=", $one->getchannels;
$one->write( file=>"one.gif" );

my $raw;
$one->write( data=>\$raw, type=>"raw",
             raw_interleave=>0, raw_storechannels=>1 ) or die $one->errstr;

open ONE, ">one.raw" or die $!;
print ONE $raw;
close ONE;


my $two = Imager->new;
$two->read( data=>$raw, type=>"raw",
            xsize=>100, ysize=>100,
            raw_interleave => 0, raw_datachannels=>1 ) or die $two->errstr;
warn "two channels=", $two->getchannels;
$two->write( file=>"two.gif" ) or die $two->errstr;
