#! /usr/bin/perl
$|++;

use IO::Socket;
use IO::Select;
use Data::Dumper;

################################################################################

sub BEGIN
{
  $Peer = 'localhost';
}

################################################################################

sub Init_socket
{
  my($Sock) = new IO::Socket::INET (
		"PeerAddr" => $Peer,
		"PeerPort" => 2040,
		"Proto" => "tcp",
		);
  # die "Socket could not be created : $!" unless $Sock;
  return($Sock);
}

################################################################################

sub Post_log
{
  my($Log) = @_;
  my($Response) = "";
  my($Sent_size);
  my($Rw_socket) = Init_socket();
  my($Size) = pack("N", length($Log));
      $Sent_size = syswrite($Rw_socket, $Size, length($Size));
      $Sent_size = syswrite($Rw_socket, "Log_", 4);
      $Sent_size = syswrite($Rw_socket, 'KEEP', 4);
      $Sent_size = syswrite($Rw_socket, $Log, length($Log));
  close($Rw_socket);
  return();
}

################################################################################

sub main
{
  Post_log('This is a test.');
}

################################################################################

main();
