#!/usr/bin/env perl

use 5.008;

use strict;
use warnings;

use Getopt::Long 2.33 qw{ VersionMessage :config auto_version };
use Pod::Usage;

our $VERSION = '2.48';

my %opt;

GetOptions( \%opt,
    help => sub { pod2usage( { -verbose => 2 } ) },
) or pod2usage( { -verbose => 0 } );

{
    open my $fh, '>', \( my $buffer )
	or die "Failed to open scalar ref: $!";

    VersionMessage( { -exitval => 'NOEXIT', -output => $fh } );

    local $\ = "\n";
    print STDERR 'Output was to ', defined $buffer ?
	'-output file handle' : 'STDERR';

    exit( defined $buffer ? 0 : 1 );
}

__END__

=head1 TITLE

check - Check Getopt::Long::VersionMessage's handling of -output

=head1 SYNOPSIS

 check
 check -help
 check -version

=head1 OPTIONS

=head2 -help

This option displays the documentation for this script. The script then
exits.

=head2 -version

This option displays the version of this script. The script then exits.

=head1 DETAILS

This Perl script calls C<Getopt::Long::VersionMessage> and attempts to
use the documented interface to capture the output in a scalar. If the
scalar is defined after the call, the attempt is considered to have
succeeded, otherwise it is considered to have failed. Success or failure
are logged to C<STDERR>, and reflected in the exit status of C<0> or
C<1> respectively.

=head1 AUTHOR

Johan Vromans (jvromans@squirrel.nl)

=head1 COPYRIGHT AND LICENSE

Copyright (C) 2016 by Thomas R. Wyant, III

This program is free software; you can redistribute it and/or modify it
under the same terms as Perl 5.10.0. For more details, see the full text
of the licenses in the directory LICENSES.

This program is distributed in the hope that it will be useful, but
without any warranty; without even the implied warranty of
merchantability or fitness for a particular purpose.

=cut

# ex: set textwidth=72 :
