#!/usr/bin/perl -wT

use strict;
use warnings;
use diagnostics;
use HTTP::Request;
use IO::Lambda qw(:lambda);
use IO::Lambda::HTTP qw(http_request);

lambda {
	foreach my $req (
		'http://www.ennisbrassband.com/links.aspx',
		'http://www.callingtontownband.com/onemoment.mp3',
		'http://www.callingtontownband.com/whowants.mp3',
		'http://www.callingtontownband.com/deep.mp3',
		'http://www.callingtontownband.com/trel.mp3',
		'http://www.callingtontownband.com/index.htm',
		'http://www.callingtontownband.com/dambust.mp3',
		'http://www.callingtontownband.com/freeworld.mp3',
		'http://www.callingtontownband.com/ctbmarch.mp3',
		'http://www.callingtontownband.com/largo.mp3',
		'http://www.callingtontownband.com/rockout.mp3',
		'http://www.callingtontownband.com/aces.mp3',
		'http://www.templemoreband.com/Events.htm',
		'http://www.templemoreband.com/Vacancies.htm',
		'http://www.templemoreband.com/Gallery.htm',
		'http://www.templemoreband.com/Members.htm',
		'http://www.templemoreband.com/Musical%20Director.htm',
		'http://www.templemoreband.com/Latest%20news.htm',
		'http://www.templemoreband.com/Band%20History.htm',
		'http://www.templemoreband.com/Audio.htm',
		'http://www.rhylsilverband.co.uk/Links.html',
		'http://www.rhylsilverband.co.uk/HomePage.html',
		'http://www.rhylsilverband.co.uk/RSB%20Style%20Sheet.css',
		'http://www.honitonband.co.uk/7.html',
		'http://www.honitonband.co.uk/index.html',
		'http://www.honitonband.co.uk/8.html',
		'http://www.honitonband.co.uk/6.html',
		'http://www.honitonband.co.uk/4.html',
		'http://www.honitonband.co.uk/goodies/PageLayout/css/default.css',
		'http://www.honitonband.co.uk/3.html',
		'http://www.honitonband.co.uk/gronau_2008_22.html',
		'http://www.honitonband.co.uk/5.html',
		'http://www.honitonband.co.uk/site_map.html',
		'http://www.honitonband.co.uk/10.html',
		'http://www.honitonband.co.uk/9.html',
		'http://www.honitonband.co.uk/2.html',
		'http://www.honitonband.co.uk/19.html',
		'http://www.stalybridgeoldband.org/page5.htm',
		'http://www.stalybridgeoldband.org/page4.htm',
		'http://www.stalybridgeoldband.org/page10.htm',
		'http://www.stalybridgeoldband.org/page6.htm',
		'http://www.stalybridgeoldband.org/index.htm',
		'http://www.stalybridgeoldband.org/page3.htm',
		'http://www.stalybridgeoldband.org/page8.htm',
		'http://www.stalybridgeoldband.org/page2.htm',
		'http://www.stalybridgeoldband.org/page11.htm',
		'http://www.stalybridgeoldband.org/page7.htm',
		'http://www.stalybridgeoldband.org/page9.htm',
		'http://www.ennisbrassband.com/Forum_Topics.aspx',
		'http://www.ennisbrassband.com/News_View.aspx',
		'http://www.ennisbrassband.com/events_calendar.aspx',
		'http://www.ennisbrassband.com/library_List.aspx',
		'http://www.ennisbrassband.com/Default.aspx',
		'http://www.ennisbrassband.com/contact.aspx',
		'http://www.ennisbrassband.com/Forum_Thread.aspx',
		'http://www.ennisbrassband.com/AvatarImagefetch.ashx',
		'http://www.ennisbrassband.com/news_list.aspx',
		'http://www.ennisbrassband.com/forums.css',
		'http://www.ennisbrassband.com/Member_Register.aspx',
		'http://www.ennisbrassband.com/clubsite.css',
		'http://www.ennisbrassband.com/photoalbum_list.aspx',
		'http://www.ennisbrassband.com/default.aspx',
	) {
		print $req . "\n";
		context(
		    HTTP::Request-> new(GET => $req),
		    async_dns    => 1,
		    keep_alive   => 1,
		    proxy	=> [ '192.168.1.1', '3128' ],
		);
		http_request {
		    my $res = shift;
		    if(ref($res) and ref($res) eq 'HTTP::Response') {
			print length($res-> content), " bytes\n";
		    } else {
			print "error :$res\n";
		    }
		}
	};
}-> wait;
