#!/usr/bin/perl -w

if($^O eq 'linux') {
	require Linux::loadavg;
	import Linux::loadavg;

	my @avgs = Linux::loadavg::loadavg(1);
	if($avgs[LOADAVG_1MIN] >= 2) {
		die "The system is overloaded\n";
	}
}
