#!/usr/bin/perl

use strict;
use warnings;
use File::Slurp;
use XML::Compile::WSDL11;

my $string=File::Slurp::slurp('some/file.wsdl');

for my $i (1..1000) {
    my $wsdl=XML::Compile::WSDL11->new(\$string);
    undef $wsdl;
}

<>
