#!/usr/bin/perl
#
# File: mech1
#
use warnings;
use strict;
use Data::Dumper;
use WWW::Mechanize;

my $user_pw = "password";
my $url = "http://10.50.1.102/cgi/device";
my $formname = "login";

my $mech = WWW::Mechanize->new();

# Now, fetch the URL
$mech->get($url);
print "I successfully did my get on $url.\n" if ($mech->success());
print Dumper($mech);
# die "Cannot select form $formname $!" unless ($mech->form_name($formname));
my @forms = $mech->forms();
print "Here are the forms I see:\n";

foreach my $i (@forms)  {
    print "--->>>$i<<<---\n";
}

$mech->submit_form(
    form_name => $formname,
    fields =>   { passwd  =>  $user_pw, },
    button => ' Login '
);
print Dumper($mech);

