#!/usr/bin/perl -w

use Email::Simple;

my $mail = Email::Simple->new(<<'EOM');
subject:
 =?utf-8?B?ZGVsLmljaW8udXMvbmV0d29yay9qb2VlIC0gW2Zyb20gbWlqaXRdIEJMQiBFY2MgMw==?=
content-type: text/plain

empty body
EOM

print $mail->as_string;
