-- ================================================================================
--   postgres SQL DDL Script File
-- ================================================================================


-- ===============================================================================
-- 
--   Generated by:      tedia2sql -- v1.2.12
--                      See http://tedia2sql.tigris.org/AUTHORS.html for tedia2sql author information
-- 
--   Target Database:   postgres
--   Generated at:      Tue Dec 15 13:24:07 2009
--   Input Files:       sp_columns.dia
-- 
-- ================================================================================



-- Generated SQL Constraints Drop statements
-- --------------------------------------------------------------------
--     Target Database:   postgres
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Tue Dec 15 13:24:07 2009
--     Input Files:       sp_columns.dia



-- Generated Permissions Drops
-- --------------------------------------------------------------------
--     Target Database:   postgres
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Tue Dec 15 13:24:07 2009
--     Input Files:       sp_columns.dia




-- Generated SQL View Drop Statements
-- --------------------------------------------------------------------
--     Target Database:   postgres
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Tue Dec 15 13:24:07 2009
--     Input Files:       sp_columns.dia



-- Generated SQL Schema Drop statements
-- --------------------------------------------------------------------
--     Target Database:   postgres
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Tue Dec 15 13:24:07 2009
--     Input Files:       sp_columns.dia

drop table users cascade ;


-- Generated SQL Schema
-- --------------------------------------------------------------------
--     Target Database:   postgres
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Tue Dec 15 13:24:07 2009
--     Input Files:       sp_columns.dia


-- users
create table users (
  id                        serial,
  first                     text not null,
  last                      text,
  UNIQUE (first, last)
) ;



-- Generated SQL Views
-- --------------------------------------------------------------------
--     Target Database:   postgres
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Tue Dec 15 13:24:07 2009
--     Input Files:       sp_columns.dia




-- Generated Permissions
-- --------------------------------------------------------------------
--     Target Database:   postgres
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Tue Dec 15 13:24:07 2009
--     Input Files:       sp_columns.dia



-- Generated SQL Insert statements
-- --------------------------------------------------------------------
--     Target Database:   postgres
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Tue Dec 15 13:24:07 2009
--     Input Files:       sp_columns.dia



-- Generated SQL Constraints
-- --------------------------------------------------------------------
--     Target Database:   postgres
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Tue Dec 15 13:24:07 2009
--     Input Files:       sp_columns.dia


