#!/bin/sh

for dir in 1 2 3 4 5 6 7 8 9 10 11 12; do
  for subdir in 1 2 3 4 5 6 7 8 9 10 11 12; do
    mkdir -p $dir/$subdir
    for file in 1 2 3 4 5 6 7 8 9 10 11 12; do
      touch $dir/$subdir/file.$file
    done
  done
done
