#!/usr/bin/env perl
use strict; use warnings; $| = 1;

# store in file ttt
# call as "PERL5DB='sub DB::DB {}' perl -d ttt"
# it reports negative line numbers in the values of %DB::sub
#
# debuggers and profilers tend not to expect negative line numbers
# and may be thrown (nytprofhtml used to hang)

{
    package Problematic;
    use strict; use warnings;

    use MooseX::Declare;


    use Moose::Util::TypeConstraints;
    BEGIN { subtype 'Problematic::Soltab' => as 'HashRef[Int]' }

    class Problematic {

        method _sol_words ($class: Problematic::Soltab $soltab) {
            # blank line between { and } needed to trigger the effect
        }
    }
}

# report on %DB::sub
print "MXD v.$MooseX::Declare::VERSION\n";
my @neg = grep $DB::sub{$_} =~ /:-\d+/, keys %DB::sub;
print "$_ => $DB::sub{$_}\n" for @neg;

__END__
